### ISSUE TITLE
The sequence of the metrics in the eval tool doesn't match with the title?

### ISSUE THREAD

**Issue by wangzinanhl** [liyingying0113/rope3d-dataset-tools#4]
should be AGD4-m AGD4-90 AGD-99
`range\ttotal\tR_s\tACS\tAOS\tASS\tAGD-rel\tAdded\tAGD4-90\tAGD-99\tAGD4-m\tmean-m\tQ99-m\t
all\t{:d}\t{:s}\t{:.3f}\t{:.3f}\t{:.3f}\t{:.3f}\t{:.3f}\t{:.3f}\t{:.3f}\t{:.3f}\t{:.3f}\t{:.3f}
    '''.format(len(list_rerr_all),
    R_score,
    ACS, 
    AOS, 
    ASS, 
    AGD4_relative,
    (ACS + AOS + ASS + AGD4_relative) / 4.0,
    AGD4_abs, 
    AGD4_Q90, 
    AGD4_Q99, 
    numpy.mean(list_rerr_all_2),
    numpy.percentile(list_rerr_all_2,99)`

**Comment by liyingying0113** [comment]
Thank you @wangzinanhl ，and we've fixed it.
